### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by endercrest** [endercrest/ColorCube#101]
Reported By Anisa321.

```{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Arial;}}
{\colortbl ;\red0\green0\blue255;\red255\green0\blue0;}
\viewkind4\uc1\pard\cf1\fs18 12/29/2016 9:27:53 PM [INFO] [ColorCube] Disabling ColorCube v0.7.0\par
12/29/2016 9:27:53 PM [SEVERE] Error occurred while disabling ColorCube v0.7.0 (Is it up to date?)\par
\cf2 12/29/2016 9:27:53 PM java.lang.NullPointerException\par
12/29/2016 9:27:53 PM \tab at com.endercrest.colorcube.MessageManager.log(MessageManager.java:48) ~[?:?]\par
12/29/2016 9:27:53 PM \tab at com.endercrest.colorcube.ColorCube.onDisable(ColorCube.java:34) ~[?:?]\par
12/29/2016 9:27:53 PM \tab at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[spigot.jar.jar:git-Spigot-a9631d2-67b2424]\par
12/29/2016 9:27:53 PM \tab at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot.jar.jar:git-Spigot-a9631d2-67b2424]\par
12/29/2016 9:27:53 PM \tab at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar.jar:git-Spigot-a9631d2-67b2424]\par
12/29/2016 9:27:53 PM \tab at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot.jar.jar:git-Spigot-a9631d2-67b2424]\par
12/29/2016 9:27:53 PM \tab at org.bukkit.craftbukkit.v1_10_R1.CraftServer.disablePlugins(CraftServer.java:341) [spigot.jar.jar:git-Spigot-a9631d2-67b2424]\par
12/29/2016 9:27:53 PM \tab at net.minecraft.server.v1_10_R1.MinecraftServer.stop(MinecraftServer.java:460) [spigot.jar.jar:git-Spigot-a9631d2-67b2424]\par
12/29/2016 9:27:54 PM \tab at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:608) [spigot.jar.jar:git-Spigot-a9631d2-67b2424]\par
12/29/2016 9:27:54 PM \tab at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]\par
}```

**Comment by endercrest** [comment]
This has now been patched, this will become available in 0.7.1.
