### ISSUE TITLE
Null Pointer when System.yml does not exist

### ISSUE THREAD

**Issue by endercrest** [endercrest/ColorCube#78]
Null Pointer is thrown by LobbyManager

```java.lang.NullPointerException
        at com.endercrest.colorcube.LobbyManager.loadSigns(LobbyManager.java:127) ~[?:?]
        at com.endercrest.colorcube.LobbyManager.setup(LobbyManager.java:33) ~[?:?]
        at com.endercrest.colorcube.ColorCube$Startup.run(ColorCube.java:93) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-f950f8e-7e02867]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-f950f8e-7e02867]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot.jar:git-Spigot-f950f8e-7e02867]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-f950f8e-7e02867]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-f950f8e-7e02867]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-f950f8e-7e02867]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]```

**Comment by endercrest** [comment]
This is obsolete due to the rewrite of the storage system.
