### ISSUE TITLE
Colorcube Startup Error

### ISSUE THREAD

**Issue by demonslayer147** [endercrest/ColorCube#86]
Hi,
I'm using spigot 1.11 and ColorCube 0.7.0 Snapshot build and whenever server startup this error will appear in console

`[23:50:22] [Server thread/WARN]: [ColorCube] Task #450 for ColorCube v0.7.0-R0.1-SNAPSHOT generated an exception
java.lang.NullPointerException
	at com.endercrest.colorcube.migration.MigrationService.migrate20161215(MigrationService.java:287) ~[?:?]
	at com.endercrest.colorcube.migration.MigrationService.runMigration(MigrationService.java:25) ~[?:?]
	at com.endercrest.colorcube.ColorCube$Startup.run(ColorCube.java:80) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-f950f8e-4d99fed]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [minecraft_server.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [minecraft_server.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [minecraft_server.jar:git-Spigot-f950f8e-4d99fed]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [minecraft_server.jar:git-Spigot-f950f8e-4d99fed]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]` 

I try downgrade back to release(0.6.1) version, delete the config file and let it regen, and still happening. Is there something wrong on my end or the plugin. I also have installed the plugin that is listed on the requirement list but still have no luck. Thanks in advance

**Comment by endercrest** [comment]
Hey, is this the first time ever starting up ColorCube where you have no configs generated?

**Comment by endercrest** [comment]
This has been fixed in V0.7.0-R0.2-SNAPSHOT. I recommend downloading that snapshot and giving it another shot.  You can download it from https://github.com/endercrest/ColorCube/releases/tag/V0.7.0-R0.2-SNAPSHOT. This update will also soon be posted on bukkit dev as an alpha version. Thanks for the Report!
