### ISSUE TITLE
The command [] [] returned an error

### ISSUE THREAD

**Issue by demonslayer147** [endercrest/ColorCube#92]
So the crashing on start up fixed now there is a new error that thrown from the console. Whenever I trying to create a lobby spawn or create a arena it throw an error to the console 

`[00:25:23] [Server thread/INFO]: DatAwesomeDude issued server command: /colorcube setgloballobbyspawn
[00:25:23] [Server thread/WARN]: java.lang.NullPointerException
[00:25:23] [Server thread/WARN]: 	at com.endercrest.colorcube.SettingsManager.setGlobalLobbySpawn(SettingsManager.java:593)
[00:25:23] [Server thread/WARN]: 	at com.endercrest.colorcube.commands.admin.SetGlobalLobbySpawn.onCommand(SetGlobalLobbySpawn.java:15)
[00:25:23] [Server thread/WARN]: 	at com.endercrest.colorcube.CommandHandler.onCommand(CommandHandler.java:129)
[00:25:23] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:25:23] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[00:25:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649)
[00:25:23] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335)
[00:25:23] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170)
[00:25:23] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[00:25:23] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[00:25:23] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[00:25:23] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[00:25:23] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[00:25:23] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[00:25:23] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739)
[00:25:23] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[00:25:23] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[00:25:23] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[00:25:23] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)`

Did I missed something?

**Comment by endercrest** [comment]
No, this seems to be a different problem. I am investigating now.

**Comment by endercrest** [comment]
@demonslayer147 Thanks for the reporting, you are catching some of the residual bugs due to the large rewrite of systems.

**Comment by demonslayer147** [comment]
Alright, I'm just tryin to help

**Comment by endercrest** [comment]
@demonslayer147 Alright, this bug and a couple more have been fixed in V0.7.0-R0.3-SNAPSHOT. https://github.com/endercrest/ColorCube/releases/tag/V0.7.0-R0.3-SNAPSHOT. Let me know how that one goes, hopefully you will be able to correctly get everything setup now.

**Comment by demonslayer147** [comment]
Went really well and it is function correctly as it should be. However, I just wanna ask do you have a scoreboard built in because for some reason I can't tell which team have the most block painted during the game. I just wanted to know if my scoreboard conflict with your plugin scoreboard (if u have one)

**Comment by endercrest** [comment]
@demonslayer147 At the moment it doesn't show what team is in the lead, but I will gladly add that as an option to an arena. If you could please create a new issue with all the details I can maybe try to sneak it into 0.7.0.
